name: Scrape Data

permissions:
  contents: write

on:
  schedule:
    # Runs every day at 4am UTC
    - cron: '0 4 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false    # important: allow using a custom PAT for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r data_sourcing/requirements.txt

      - name: Run scraper
        run: |
          python data_sourcing/main.py

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Stage and commit changes (if any)
        run: |
          git add assets/assets/
          # exit code 1 if no changes; the `|| true` avoids failing the job
          git diff --staged --quiet || git commit -m "Update scraped data [skip ci]"

      - name: Push changes using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # replace origin with PAT-backed URL so push authenticates with your token
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/PaMcD/mma_matrix_web.git
          # push to main (change target branch if you prefer)
          git push --set-upstream origin HEAD:main --follow-tags
